document:
  name: Regolamento sul Decentramento del comune di Palermo
  description: |
    Regolamento sul Decentramento del comune di Palermo.    
  tags:
    - decentramento
    - regolamento
    - comune Palermo
